<?php 

function mr_links_node_view($node, $view_mode, $langcode) {
  $links = array();
  if(context_isset('context','theology')) {
    $href = 'http://micahredding.com/xn';
  } else {
    $href = 'http://micahredding.com/curve';
  }

  $links[] = array(
      'title' => '• Get essays like this by email', 
      'href' => $href,
      'attributes' => array(
          'target'=>'_blank',
          'rel' => 'nofollow',
       ),    
  );  


  $node->content['links']['mr'] = array(
      '#theme' => 'links',
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
  );


}