<?php

function mrblocks_block_info() {
  return array(
    'site-title' => array(
      'info' => t('Site Title'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-title-life' => array(
      'info' => t('Section Title Life'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-photo-life' => array(
      'info' => t('Section Photo Life'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-title-theology' => array(
      'info' => t('Section Title Theology'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-photo-theology' => array(
      'info' => t('Section Photo Theology'),
      'cache' => DRUPAL_NO_CACHE,
    ),

    'site-message' => array(
      'info' => t('Site Message'),
      'cache' => DRUPAL_NO_CACHE,
    ),

    'mr-nav' => array(
      'info' => t('MR Custom Nav'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

function mrblocks_block_view($id) {
  switch($id) {
    case 'site-title':
      return array(
        'subject' => 'Site Name',
        'content' => '<div id="site-name">
              <strong>
                <a href="' . base_path() . '" title="Home" rel="home">
                  <span>Micah Redding</span>
                </a>
              </strong>
            </div>            
       ',);
    break;
    case 'section-title-life':
      return array(
        'subject' => 'Section Title Life on the Curve',
        'content' => '<h1 class="section">
                <a href="' . base_path() . 'life" title="Home" rel="home">Life on the Curve</a>
            </h1>',);
    break;
    case 'section-photo-life':
      return array(
        'subject' => 'Section Photo Life on the Curve',
        'content' => '<a href="' . base_path() . 'life" title="Home" rel="home">
            <img src="' . base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/curve.jpg" /></a>',);
    break;
    case 'section-title-theology':
      return array(
        'subject' => 'Section Title Theology',
        'content' => '<h1 class="section">
                <a href="' . base_path() . 'theology" title="Home" rel="home">Christianity Against Religion</a>
            </h1>',);
    break;
    case 'section-photo-theology':
      return array(
        'subject' => 'Section Photo Life on the Curve',
        'content' => '<a href="' . base_path() . 'theology" title="Home" rel="home">
            <img src="' . base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/xn.jpg" /></a>',);
    break;

    case 'site-message':
      return array(
        'subject' => 'Site Message',
        'content' => 'Random musings, unconventional theological reflections,   and memos from the edge of my human experience.',
      );
    break;
    case 'mr-nav':
      return array(
        'subject' => NULL,
        'content' => theme('item_list', array('items' => array(
          'Twitter' => _prepare_tweet(),
          'Email' => _prepare_subscribe(),
        ))),
      );
    break;
  }
}

function _prepare_tweet() {
  $page_title = drupal_get_title();
  if(empty($page_title)) {
    $page_title = 'Micah Redding: Life on the Curve';
  }
  $url = url(drupal_lookup_path('alias',current_path()), array('absolute' => TRUE));
  $status = '"' . $page_title . '" ' . $url . ' via @micahtredding';
  $img = base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/twitter.png';

  $array = array();
  $array['title'] = '<img src="'. $img .'" alt="Post to Twitter" title="Post to Twitter"> Post to Twitter';
  $array['href'] = 'http://twitter.com/';
  $array['attributes'] = array(
    'class' => 'tweet',
    'rel' => 'nofollow',
    'target' => '_blank',
  );
  $array['query'] = array(
    'status' => $status,
  );
  $array['html'] = TRUE;

  $tweet = l($array['title'], $array['href'], array('attributes' => $array['attributes'], 'query' => $array['query'], 'absolute' => TRUE, 'html' => $array['html']));
  return $tweet;
}

function _prepare_subscribe() {
  $href = '';
  if(context_isset('context','theology')) {
    $href = 'http://micahredding.com/xn';
  } else {
    $href = 'http://micahredding.com/curve';
  }

  $img = base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/mail.png';

  return '<a href="' . $href . '"><img src="' . $img . '" /> Get essays by email</a>';
}
