<?php

function mrblocks_block_info() {
  return array(
    'site-title' => array(
      'info' => t('Site Title'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-title-life' => array(
      'info' => t('Section Title Life'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-photo-life' => array(
      'info' => t('Section Photo Life'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-title-theology' => array(
      'info' => t('Section Title Theology'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'section-photo-theology' => array(
      'info' => t('Section Photo Theology'),
      'cache' => DRUPAL_NO_CACHE,
    ),

    'site-message' => array(
      'info' => t('Site Message'),
      'cache' => DRUPAL_NO_CACHE,
    ),

    'mr-nav' => array(
      'info' => t('MR Custom Nav'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

function mrblocks_block_view($id) {
  switch($id) {
    case 'site-title':
      return array(
        'subject' => 'Site Name',
        'content' => '<div id="site-name">
              <strong>
                <a href="' . base_path() . '" title="Home" rel="home">
                  <span>Micah Redding</span>
                </a>
              </strong>
            </div>
       ',);
    break;
    case 'section-title-life':
      return array(
        'subject' => 'Section Title Life on the Curve',
        'content' => '<h1 class="section">
                <a href="' . base_path() . 'life" title="Home" rel="home">Life on the Curve</a>
            </h1>',);
    break;
    case 'section-photo-life':
      return array(
        'subject' => 'Section Photo Life on the Curve',
        'content' => '<a href="' . base_path() . 'life" title="Home" rel="home">
            <img src="' . base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/curve.jpg" /></a>',);
    break;
    case 'section-title-theology':
      return array(
        'subject' => 'Section Title Theology',
        'content' => '<h1 class="section">
                <a href="' . base_path() . 'theology" title="Home" rel="home">Christianity Against Religion</a>
            </h1>',);
    break;
    case 'section-photo-theology':
      return array(
        'subject' => 'Section Photo Life on the Curve',
        'content' => '<a href="' . base_path() . 'theology" title="Home" rel="home">
            <img src="' . base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/xn.jpg" /></a>',);
    break;

    case 'site-message':
      return array(
        'subject' => 'Site Message',
        'content' => 'Random musings, unconventional theological reflections,   and memos from the edge of my human experience.',
      );
    break;
    case 'mr-nav':
      return array(
        'subject' => NULL,
        'content' =>
          '<p>' . _prepare_subscribe() . '</p>' .
          '<p>' . _prepare_rss() . '</p>' .
          '<p>' . _prepare_tweet() . '</p>' .
          '<p>' . _prepare_fb() . '</p>',
      );
    break;
  }
}

function _prepare_rss() {
  $attributes = array();
  $attributes['class'] = 'rss';
  $attributes['target'] = '_blank';
  $title = '<i class="fa fa-rss"></i> RSS Feed';
  $rss = l($title, 'http://micahredding.com/blog/rss.xml', array('attributes' => $attributes, 'absolute' => TRUE, 'html' => TRUE));
  return $rss;
}

function _prepare_tweet() {
  $page_title = drupal_get_title();
  if(empty($page_title)) {
    $page_title = 'Micah Redding: Life on the Curve';
  }
  $url = current_path();
  if($url == 'node') {
    $url = drupal_lookup_path('alias',current_path());
  }
  $img = base_path() . drupal_get_path('module', 'mrblocks') . '/assets/images/twitter.png';

  $array = array();
  $array['title'] = '<i class="fa fa-twitter"></i> Post to Twitter';
  $array['href'] = 'http://twitter.com/';
  $array['attributes'] = array(
    'class' => 'tweet',
    'rel' => 'nofollow',
    'target' => '_blank',
  );

  $tweet_path = _prepare_tweet_path($page_title, $url);

  $tweet = l($array['title'], $tweet_path, array('attributes' => $array['attributes'], 'absolute' => TRUE, 'html' => TRUE));
  return $tweet;
}

function _prepare_fb() {
  $url = current_path();
  if($url == 'node') {
    $url = '<front>';
  }
  $url = url($url, array('absolute' => TRUE));
  return '<div class="fb-like" data-href="' . $url . '" data-width="450" data-layout="button_count" data-show-faces="true" data-send="true" style="max-width:200px;"></div>';
}

function _prepare_tweet_path($page_title, $path) {
  $url = url($path, array('absolute' => TRUE));
  $status = '"' . $page_title . '" ' . $url . ' via @micahtredding';

  $options = array();
  $options['absolute'] = TRUE;
  $options['query'] = array(
    'status' => $status,
  );

  $tweet = url('http://twitter.com/', $options);
  return $tweet;
}

function _prepare_subscribe() {
  $href = '';
  if(context_isset('context','theology')) {
    $href = 'http://micahredding.com/xn';
  } else {
    $href = 'http://micahredding.com/curve';
  }

  return '<a href="' . $href . '"><i class="fa fa-envelope-o"></i> Get essays by email</a>';
}
